name: Helpjuice CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-matrix: ${{ steps.get-python-versions-action.outputs.latest-python-versions }}
    steps:
      - uses: snok/latest-python-versions@v1
        id: get-python-versions-action
        with:
          min-version: 3.7

  test:
    needs: [get-python-versions]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.get-python-versions.outputs.python-matrix) }}

    steps:
      - name: Test on ${{ github.repository }}
        run: echo ${{ matrix.python-version }}
    # uses: ./.github/workflows/test.yml
    # with:
    #   python-version: ${{ matrix.python-version }}
