name: Create release

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read package version
        uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: pyproject.toml
          field: tool.poetry.version

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ format('v{0}', steps.read_toml.outputs.value) }}
