name: Python 🐍 package 📦 test

on:
  workflow_call:
    inputs:
      python-version:
        description: The version of Python to use for this workflow.
        default: 3.10
        type: number

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Specify Poetry Python version
        run: poetry env use ${{ inputs.python-version }}

      - name: Install dependencies
        run: poetry install --with test --no-interaction

      - name: Run tests
        run: poetry run pytest --cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
